"use client";

import Image from "next/image";
import Link from "next/link";
import { Calendar, ChevronRight, FileText } from "lucide-react";
import { useGetPublicResumesQuery } from "@/lib/services/portfolioApi";
import { formatDate } from "@/helpers/formatDate";

const PublicResumeList = () => {
  const { data: resumes, isLoading } = useGetPublicResumesQuery();

  return (
    <div className='min-h-screen text-slate-950 dark:text-slate-100 relative overflow-hidden'>
      <div className='absolute inset-0 page-aurora -z-10 dark:hidden' />
      <div className='absolute inset-0 page-aurora-dark -z-10 hidden dark:block' />
      <div className='absolute inset-0 bg-grid opacity-20 -z-10 dark:hidden' />
      <div className='absolute inset-0 bg-grid-dark opacity-10 -z-10 hidden dark:block' />

      <div className='max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 py-20'>
        <div className='flex flex-col lg:flex-row lg:items-end lg:justify-between gap-6'>
          <div>
            <p className='text-xs uppercase tracking-[0.3em] text-slate-500'>
              Resume Library
            </p>
            <h1 className='mt-3 text-4xl sm:text-5xl font-semibold text-slate-900 dark:text-white'>
              Public resumes from the portfolio platform
            </h1>
          </div>
          <p className='max-w-xl text-base text-slate-600 dark:text-slate-400'>
            Browse published resumes generated by the backend. Each profile is
            structured with skills, experience, and contact details ready for
            download or review.
          </p>
        </div>

        {isLoading ? (
          <div className='mt-12 grid gap-6 md:grid-cols-2'>
            {[...Array(4)].map((_, i) => (
              <div
                key={i}
                className='h-56 rounded-3xl border border-slate-200/60 bg-white/70 shadow-sm animate-pulse dark:border-slate-700/60 dark:bg-slate-900/70'
              />
            ))}
          </div>
        ) : resumes && resumes.length > 0 ? (
          <div className='mt-12 grid gap-6 md:grid-cols-2'>
            {resumes.map((resume) => {
              const contact = resume.contactInfo || {};
              const skills = resume.skills || [];
              const visibleSkills = skills.slice(0, 6);
              const extraSkills = skills.length - visibleSkills.length;

              return (
                <article
                  key={resume.id}
                  className='rounded-3xl border border-slate-200/70 bg-white/85 p-6 shadow-sm backdrop-blur transition-shadow duration-300 hover:shadow-lg dark:border-slate-700/60 dark:bg-slate-900/80'
                >
                  <div className='flex items-center gap-4'>
                    <div className='flex h-14 w-14 items-center justify-center rounded-2xl bg-slate-900 text-white shadow-lg shadow-slate-900/20'>
                      <FileText className='h-7 w-7' />
                    </div>
                    <div>
                      <h2 className='text-2xl font-semibold text-slate-900 dark:text-white'>
                        {resume.title}
                      </h2>
                      <div className='mt-2 flex items-center gap-2 text-xs text-slate-500 dark:text-slate-400'>
                        <Calendar className='h-3 w-3' />
                        <span>{formatDate(resume.createdAt)}</span>
                      </div>
                    </div>
                  </div>

                  <p className='mt-4 text-sm text-slate-600 dark:text-slate-300'>
                    {resume.summary ||
                      "A structured resume generated through the portfolio backend."}
                  </p>

                  {resume.professionalPhoto && (
                    <div className='mt-4 flex items-center gap-3 rounded-2xl border border-slate-200/70 bg-slate-50/80 p-3 dark:border-slate-700/60 dark:bg-slate-950/60'>
                      <Image
                        src={resume.professionalPhoto}
                        alt={resume.title}
                        width={48}
                        height={48}
                        className='h-12 w-12 rounded-xl object-cover'
                      />
                      <div className='text-xs text-slate-600 dark:text-slate-300'>
                        Professional photo attached
                      </div>
                    </div>
                  )}

                  {skills.length > 0 && (
                    <div className='mt-5 flex flex-wrap gap-2'>
                      {visibleSkills.map((skill) => (
                        <span
                          key={skill}
                          className='rounded-full border border-slate-200 bg-white/70 px-3 py-1 text-xs text-slate-700 shadow-sm dark:border-slate-700/60 dark:bg-slate-900/70 dark:text-slate-200'
                        >
                          {skill}
                        </span>
                      ))}
                      {extraSkills > 0 && (
                        <span className='rounded-full border border-dashed border-slate-300 px-3 py-1 text-xs text-slate-500 dark:border-slate-600 dark:text-slate-400'>
                          +{extraSkills} more
                        </span>
                      )}
                    </div>
                  )}

                  <div className='mt-6 flex flex-col gap-2 text-xs text-slate-500 dark:text-slate-400'>
                    {contact.email && <span>Email: {contact.email}</span>}
                    {contact.phone && <span>Phone: {contact.phone}</span>}
                    {contact.location && <span>Location: {contact.location}</span>}
                  </div>

                  <div className='mt-6'>
                    <Link
                      href={`/resume/${resume.id}`}
                      className='inline-flex items-center gap-2 rounded-full border border-slate-300 bg-white/80 px-5 py-2 text-xs font-semibold text-slate-800 shadow-sm backdrop-blur transition hover:-translate-y-0.5 hover:border-slate-400 dark:border-slate-700 dark:bg-slate-900/60 dark:text-slate-100'
                    >
                      View Resume
                      <ChevronRight className='h-4 w-4' />
                    </Link>
                  </div>
                </article>
              );
            })}
          </div>
        ) : (
          <div className='mt-16 rounded-3xl border border-dashed border-slate-300/80 bg-white/70 p-8 text-center text-sm text-slate-600 dark:border-slate-700/60 dark:bg-slate-900/60 dark:text-slate-300'>
            No public resumes are available yet. Publish one from the admin
            dashboard to display it here.
          </div>
        )}
      </div>
    </div>
  );
};

export default PublicResumeList;
